INSERT INTO PLAYER (name) VALUES ('Novak Djokovic');
INSERT INTO PLAYER (name) VALUES ('Daniil Medvedev');
INSERT INTO PLAYER (name) VALUES ('Marat Safin');
INSERT INTO PLAYER (name) VALUES ('Carlos Alcaraz');
INSERT INTO PLAYER (name) VALUES ('Roger Federer');
INSERT INTO PLAYER (name) VALUES ('Rafael Nadal');
INSERT INTO PLAYER (name) VALUES ('Jannik Sinner');
INSERT INTO PLAYER (name) VALUES ('Alexander Zverev');
INSERT INTO PLAYER (name) VALUES ('Andrey Rublev');
INSERT INTO PLAYER (name) VALUES ('Casper Ruud');
INSERT INTO PLAYER (name) VALUES ('Alex de Minaur');
INSERT into PLAYER (name) values ('L. KIVIC');
INSERT into PLAYER (name) values ('K. LAMPOT');
INSERT into PLAYER (name) values ('J. PORROT');
INSERT into PLAYER (name) values ('G. GRIMBER');
INSERT into PLAYER (name) values ('K. KUBERT');
INSERT into PLAYER (name) values ('S. SAFIN');
INSERT into PLAYER (name) values ('I. BORG');
INSERT into PLAYER (name) values ('O. PORIS');
INSERT into PLAYER (name) values ('A. GETIRM');
INSERT into PLAYER (name) values ('S. POKOR');
INSERT INTO PLAYER (name) VALUES ('Andrey Semenov');
INSERT INTO PLAYER (name) VALUES ('John Doe');
INSERT INTO PLAYER (name) VALUES ('Viktor Krum');
INSERT into PLAYER (name) values ('Edward Kallen');
INSERT into PLAYER (name) values ('Mike Vazowsky');
INSERT into PLAYER (name) values ('Kolychev Stepan');
INSERT into PLAYER (name) values ('Albert Krivich');
INSERT into PLAYER (name) values ('Johnny');
INSERT into PLAYER (name) values ('Tony Cringe');
INSERT into PLAYER (name) values ('Antony Volk');

INSERT INTO MATCH (player1, player2, winner) values (20, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (12, 1, 12);
INSERT INTO MATCH (player1, player2, winner) values (22, 10, 22);
INSERT INTO MATCH (player1, player2, winner) values (6, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (6, 23, 23);
INSERT INTO MATCH (player1, player2, winner) values (21, 20, 21);
INSERT INTO MATCH (player1, player2, winner) values (11, 13, 13);
INSERT INTO MATCH (player1, player2, winner) values (9, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (2, 21, 2);
INSERT INTO MATCH (player1, player2, winner) values (20, 15, 20);
INSERT INTO MATCH (player1, player2, winner) values (13, 21, 21);
INSERT INTO MATCH (player1, player2, winner) values (8, 11, 11);
INSERT INTO MATCH (player1, player2, winner) values (23, 17, 23);
INSERT INTO MATCH (player1, player2, winner) values (5, 30, 5);
INSERT INTO MATCH (player1, player2, winner) values (1, 16, 16);
INSERT INTO MATCH (player1, player2, winner) values (25, 18, 18);
INSERT INTO MATCH (player1, player2, winner) values (14, 19, 19);
INSERT INTO MATCH (player1, player2, winner) values (27, 12, 27);
INSERT INTO MATCH (player1, player2, winner) values (13, 20, 20);
INSERT INTO MATCH (player1, player2, winner) values (6, 16, 6);
INSERT INTO MATCH (player1, player2, winner) values (22, 28, 22);
INSERT INTO MATCH (player1, player2, winner) values (22, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (17, 4, 4);
INSERT INTO MATCH (player1, player2, winner) values (6, 11, 11);
INSERT INTO MATCH (player1, player2, winner) values (25, 27, 25);
INSERT INTO MATCH (player1, player2, winner) values (15, 10, 15);
INSERT INTO MATCH (player1, player2, winner) values (24, 18, 24);
INSERT INTO MATCH (player1, player2, winner) values (28, 10, 28);
INSERT INTO MATCH (player1, player2, winner) values (5, 17, 17);
INSERT INTO MATCH (player1, player2, winner) values (20, 24, 20);
INSERT INTO MATCH (player1, player2, winner) values (11, 20, 11);
INSERT INTO MATCH (player1, player2, winner) values (16, 23, 16);
INSERT INTO MATCH (player1, player2, winner) values (3, 7, 7);
INSERT INTO MATCH (player1, player2, winner) values (22, 16, 16);
INSERT INTO MATCH (player1, player2, winner) values (19, 12, 12);
INSERT INTO MATCH (player1, player2, winner) values (1, 16, 1);
INSERT INTO MATCH (player1, player2, winner) values (21, 4, 4);
INSERT INTO MATCH (player1, player2, winner) values (26, 6, 6);
INSERT INTO MATCH (player1, player2, winner) values (25, 22, 22);
INSERT INTO MATCH (player1, player2, winner) values (11, 5, 5);
INSERT INTO MATCH (player1, player2, winner) values (9, 15, 15);
INSERT INTO MATCH (player1, player2, winner) values (14, 27, 14);
INSERT INTO MATCH (player1, player2, winner) values (18, 7, 7);
INSERT INTO MATCH (player1, player2, winner) values (17, 5, 5);
INSERT INTO MATCH (player1, player2, winner) values (12, 17, 12);
INSERT INTO MATCH (player1, player2, winner) values (5, 1, 5);
INSERT INTO MATCH (player1, player2, winner) values (6, 3, 3);
INSERT INTO MATCH (player1, player2, winner) values (29, 25, 29);
INSERT INTO MATCH (player1, player2, winner) values (15, 24, 24);
INSERT INTO MATCH (player1, player2, winner) values (1, 16, 16);
INSERT INTO MATCH (player1, player2, winner) values (24, 20, 20);
INSERT INTO MATCH (player1, player2, winner) values (19, 20, 20);
INSERT INTO MATCH (player1, player2, winner) values (1, 18, 18);
INSERT INTO MATCH (player1, player2, winner) values (25, 11, 25);
INSERT INTO MATCH (player1, player2, winner) values (20, 12, 12);
INSERT INTO MATCH (player1, player2, winner) values (6, 7, 6);
INSERT INTO MATCH (player1, player2, winner) values (21, 4, 21);
INSERT INTO MATCH (player1, player2, winner) values (19, 6, 19);
INSERT INTO MATCH (player1, player2, winner) values (20, 23, 23);
INSERT INTO MATCH (player1, player2, winner) values (27, 29, 27);