INSERT INTO PLAYER (name) VALUES ('Novak Djokovic');
INSERT INTO PLAYER (name) VALUES ('Daniil Medvedev');
INSERT INTO PLAYER (name) VALUES ('Marat Safin');
INSERT INTO PLAYER (name) VALUES ('Carlos Alcaraz');
INSERT INTO PLAYER (name) VALUES ('Roger Federer');
INSERT INTO PLAYER (name) VALUES ('Rafael Nadal');
INSERT INTO PLAYER (name) VALUES ('Jannik Sinner');
INSERT INTO PLAYER (name) VALUES ('Alexander Zverev');
INSERT INTO PLAYER (name) VALUES ('Andrey Rublev');
INSERT INTO PLAYER (name) VALUES ('Casper Ruud');
INSERT INTO PLAYER (name) VALUES ('Alex de Minaur');
INSERT into PLAYER (name) values ('L. KIVIC');
INSERT into PLAYER (name) values ('K. LAMPOT');
INSERT into PLAYER (name) values ('J. PORROT');
INSERT into PLAYER (name) values ('G. GRIMBER');
INSERT into PLAYER (name) values ('K. KUBERT');
INSERT into PLAYER (name) values ('S. SAFIN');
INSERT into PLAYER (name) values ('I. BORG');
INSERT into PLAYER (name) values ('O. PORIS');
INSERT into PLAYER (name) values ('A. GETIRM');
INSERT into PLAYER (name) values ('S. POKOR');

INSERT INTO MATCH (player1, player2, winner) values (1, 2, 1);
INSERT INTO MATCH (player1, player2, winner) values (3, 8, 8);
INSERT INTO MATCH (player1, player2, winner) values (5, 19, 19);
INSERT INTO MATCH (player1, player2, winner) values (8, 11, 8);
INSERT INTO MATCH (player1, player2, winner) values (12, 4, 4);
INSERT INTO MATCH (player1, player2, winner) values (8, 21, 8);
INSERT INTO MATCH (player1, player2, winner) values (9, 5, 5);
INSERT INTO MATCH (player1, player2, winner) values (15, 11, 11);
INSERT INTO MATCH (player1, player2, winner) values (10, 6, 10);
INSERT INTO MATCH (player1, player2, winner) values (14, 11, 14);
INSERT INTO MATCH (player1, player2, winner) values (20, 8, 8);
INSERT INTO MATCH (player1, player2, winner) values (19, 4, 4);
INSERT INTO MATCH (player1, player2, winner) values (16, 3, 3);
INSERT INTO MATCH (player1, player2, winner) values (17, 1, 17);
INSERT INTO MATCH (player1, player2, winner) values (20, 17, 20);
INSERT INTO MATCH (player1, player2, winner) values (21, 14, 14);
INSERT INTO MATCH (player1, player2, winner) values (4, 20, 4);
INSERT INTO MATCH (player1, player2, winner) values (7, 19, 19);
INSERT INTO MATCH (player1, player2, winner) values (17, 14, 17);