INSERT INTO PLAYER (name) VALUES ('Novak Djokovic');
INSERT INTO PLAYER (name) VALUES ('Carlos Alcaraz Garfia');
INSERT INTO PLAYER (name) VALUES ('Daniil Medvedev');
INSERT INTO PLAYER (name) VALUES ('Jannik Sinner');
INSERT INTO PLAYER (name) VALUES ('Andrey Rublev');
INSERT INTO PLAYER (name) VALUES ('Stefanos Tsitsipas');
INSERT INTO PLAYER (name) VALUES ('Alexander Zverev');
INSERT INTO PLAYER (name) VALUES ('Holger Vitus Nodskov Rune');
INSERT INTO PLAYER (name) VALUES ('Hubert Hurkacz');
INSERT INTO PLAYER (name) VALUES ('Taylor Harry Fritz');
INSERT INTO PLAYER (name) VALUES ('Casper Ruud');
INSERT into PLAYER (name) values ('Alex De Minaur');
INSERT into PLAYER (name) values ('Tommy Paul');
INSERT into PLAYER (name) values ('Grigor Dimitrov');
INSERT into PLAYER (name) values ('Karen Khachanov');
INSERT into PLAYER (name) values ('Frances Tiafoe');
INSERT into PLAYER (name) values ('Ben Shelton');
INSERT into PLAYER (name) values ('Cameron Norrie');
INSERT into PLAYER (name) values ('Nicolas Jarry');
INSERT into PLAYER (name) values ('Ugo Humbert');
INSERT into PLAYER (name) values ('Francisco Cerundolo');
INSERT INTO PLAYER (name) VALUES ('Adrian Mannarino');
INSERT INTO PLAYER (name) VALUES ('Tallon Griekspoor');
INSERT INTO PLAYER (name) VALUES ('Sebastian Korda');
INSERT into PLAYER (name) values ('Jan Lennard Struff');
INSERT into PLAYER (name) values ('Alejandro Davidovich Fokina');
INSERT into PLAYER (name) values ('Lorenzo Musetti');
INSERT into PLAYER (name) values ('Sebastian Baez');
INSERT into PLAYER (name) values ('Felix Auger Aliassime');
INSERT into PLAYER (name) values ('Tomas Martin Etcheverry');
INSERT into PLAYER (name) values ('Jiri Lehecka');
INSERT into PLAYER (name) values ('Alexander Bublik');

INSERT INTO MATCH (player1, player2, winner) values (20, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (12, 1, 12);
INSERT INTO MATCH (player1, player2, winner) values (22, 10, 22);
INSERT INTO MATCH (player1, player2, winner) values (6, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (6, 23, 23);
INSERT INTO MATCH (player1, player2, winner) values (21, 20, 21);
INSERT INTO MATCH (player1, player2, winner) values (11, 13, 13);
INSERT INTO MATCH (player1, player2, winner) values (9, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (2, 21, 2);
INSERT INTO MATCH (player1, player2, winner) values (20, 15, 20);
INSERT INTO MATCH (player1, player2, winner) values (13, 21, 21);
INSERT INTO MATCH (player1, player2, winner) values (8, 11, 11);
INSERT INTO MATCH (player1, player2, winner) values (23, 17, 23);
INSERT INTO MATCH (player1, player2, winner) values (5, 30, 5);
INSERT INTO MATCH (player1, player2, winner) values (1, 16, 16);
INSERT INTO MATCH (player1, player2, winner) values (25, 18, 18);
INSERT INTO MATCH (player1, player2, winner) values (14, 19, 19);
INSERT INTO MATCH (player1, player2, winner) values (27, 12, 27);
INSERT INTO MATCH (player1, player2, winner) values (13, 20, 20);
INSERT INTO MATCH (player1, player2, winner) values (6, 16, 6);
INSERT INTO MATCH (player1, player2, winner) values (22, 28, 22);
INSERT INTO MATCH (player1, player2, winner) values (22, 28, 28);
INSERT INTO MATCH (player1, player2, winner) values (17, 4, 4);
INSERT INTO MATCH (player1, player2, winner) values (6, 11, 11);
INSERT INTO MATCH (player1, player2, winner) values (25, 27, 25);
INSERT INTO MATCH (player1, player2, winner) values (15, 10, 15);
INSERT INTO MATCH (player1, player2, winner) values (24, 18, 24);
INSERT INTO MATCH (player1, player2, winner) values (28, 10, 28);
INSERT INTO MATCH (player1, player2, winner) values (5, 17, 17);
INSERT INTO MATCH (player1, player2, winner) values (20, 24, 20);
INSERT INTO MATCH (player1, player2, winner) values (11, 20, 11);
INSERT INTO MATCH (player1, player2, winner) values (16, 23, 16);
INSERT INTO MATCH (player1, player2, winner) values (3, 7, 7);
INSERT INTO MATCH (player1, player2, winner) values (22, 16, 16);
INSERT INTO MATCH (player1, player2, winner) values (19, 12, 12);
INSERT INTO MATCH (player1, player2, winner) values (1, 16, 1);
INSERT INTO MATCH (player1, player2, winner) values (21, 4, 4);
INSERT INTO MATCH (player1, player2, winner) values (26, 6, 6);
INSERT INTO MATCH (player1, player2, winner) values (25, 22, 22);
INSERT INTO MATCH (player1, player2, winner) values (11, 5, 5);
INSERT INTO MATCH (player1, player2, winner) values (9, 15, 15);
INSERT INTO MATCH (player1, player2, winner) values (14, 27, 14);
INSERT INTO MATCH (player1, player2, winner) values (18, 7, 7);
INSERT INTO MATCH (player1, player2, winner) values (17, 5, 5);
INSERT INTO MATCH (player1, player2, winner) values (12, 17, 12);
INSERT INTO MATCH (player1, player2, winner) values (5, 1, 5);
INSERT INTO MATCH (player1, player2, winner) values (6, 3, 3);
INSERT INTO MATCH (player1, player2, winner) values (29, 25, 29);
INSERT INTO MATCH (player1, player2, winner) values (15, 24, 24);
INSERT INTO MATCH (player1, player2, winner) values (1, 16, 16);
INSERT INTO MATCH (player1, player2, winner) values (24, 20, 20);
INSERT INTO MATCH (player1, player2, winner) values (19, 20, 20);
INSERT INTO MATCH (player1, player2, winner) values (1, 18, 18);
INSERT INTO MATCH (player1, player2, winner) values (25, 11, 25);
INSERT INTO MATCH (player1, player2, winner) values (20, 12, 12);
INSERT INTO MATCH (player1, player2, winner) values (6, 7, 6);
INSERT INTO MATCH (player1, player2, winner) values (21, 4, 21);
INSERT INTO MATCH (player1, player2, winner) values (19, 6, 19);
INSERT INTO MATCH (player1, player2, winner) values (20, 23, 23);
INSERT INTO MATCH (player1, player2, winner) values (27, 29, 27);
INSERT INTO MATCH (player1, player2, winner) values (27, 32, 32);
